name: Ansible Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install ansible
      run: |
        sudo apt update
        sudo apt install ansible -y
    
    - name: Install ansible-lint
      run: pip install ansible-lint
    
    - name: Run ansible-lint
      run: ansible-lint playbook.yml --skip-list schema[playbook]
